/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Aplikasi.Koneksi;
import aplikasiakademik.MenuUtama;

/**
 *
 * @author FLEX-5
 */
public class FormKrs extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKrs.class.getName());

    /**
     * Creates new form FormKrs
     */
    public FormKrs() {
        initComponents();
        tampilMahasiswa();
        tampilMatkul();
        tampilSemester();
        tampilData();

    }

    private void tampilMahasiswa() {

        try {

            cbMahasiswa.removeAllItems();

            cbMahasiswa.addItem("-- Pilih Mahasiswa --");

            Connection conn = Koneksi.getKoneksi();

            Statement st = conn.createStatement();

            ResultSet rs
                    = st.executeQuery("SELECT * FROM mahasiswa");

            while (rs.next()) {

                cbMahasiswa.addItem(
                        rs.getString("nim")
                        + " - "
                        + rs.getString("nama_mahasiswa")
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void tampilMatkul() {

        try {
            cbMatkul.removeAllItems();

            cbMatkul.addItem("-- Pilih Mata Kuliah --");

            Connection conn = Koneksi.getKoneksi();

            Statement st = conn.createStatement();

            ResultSet rs
                    = st.executeQuery("SELECT * FROM matkul");

            while (rs.next()) {

                cbMatkul.addItem(
                        rs.getString("kode_matkul")
                        + " - "
                        + rs.getString("nama_matkul")
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void tampilSemester() {

        cbSemester.addItem("Semester 1");
        cbSemester.addItem("Semester 2");
        cbSemester.addItem("Semester 3");
        cbSemester.addItem("Semester 4");
        cbSemester.addItem("Semester 5");
        cbSemester.addItem("Semester 6");
    }

    private void tampilData() {

        try {
            DefaultTableModel model
                    = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("NIM");
            model.addColumn("Kode Mata Kuliah");
            model.addColumn("Semester");
            model.addColumn("Tahun Ajaran");

            model.setRowCount(0);

            Connection conn = Koneksi.getKoneksi();

            String sql
                    = "SELECT krs.id, mahasiswa.nama_mahasiswa, "
                    + "matkul.nama_matkul, "
                    + "krs.semester, krs.tahun_ajaran "
                    + "FROM krs "
                    + "JOIN mahasiswa "
                    + "ON krs.nim = mahasiswa.nim "
                    + "JOIN matkul "
                    + "ON krs.kode_matkul = matkul.kode_matkul";

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nama_mahasiswa"),
                    rs.getString("nama_matkul"),
                    rs.getString("semester"),
                    rs.getString("tahun_ajaran")
                });
            }
            tblKrs.setModel(model);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void resetForm() {

        cbMahasiswa.setSelectedIndex(0);

        cbMatkul.setSelectedIndex(0);

        cbSemester.setSelectedIndex(0);

        txtTahun.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbMahasiswa = new javax.swing.JComboBox<>();
        cbMatkul = new javax.swing.JComboBox<>();
        cbSemester = new javax.swing.JComboBox<>();
        txtTahun = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKrs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORM KRS");

        jLabel2.setText("Nim                            :");

        jLabel3.setText("Kode Matkul              : ");

        jLabel4.setText("Semester                    : ");

        jLabel5.setText("Tahun Ajaran              : ");

        cbMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMahasiswa.addActionListener(this::cbMahasiswaActionPerformed);

        cbMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        tblKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKrs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTahun)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTambah)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEdit)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnKembali)))))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnKembali))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {

            Connection conn = Koneksi.getKoneksi();

            // Ambil NIM
            String mahasiswa
                    = cbMahasiswa.getSelectedItem().toString();

            String nim
                    = mahasiswa.split(" - ")[0];

            // Ambil Kode Matkul
            String matkul
                    = cbMatkul.getSelectedItem().toString();

            String kodeMatkul
                    = matkul.split(" - ")[0];

            String sql
                    = "INSERT INTO krs(nim,kode_matkul,semester,tahun_ajaran) "
                    + "VALUES(?,?,?,?)";

            PreparedStatement pst
                    = conn.prepareStatement(sql);

            pst.setString(1, nim);

            pst.setString(2, kodeMatkul);

            pst.setString(3,
                    cbSemester.getSelectedItem().toString());

            pst.setString(4,
                    txtTahun.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "KRS berhasil disimpan");

            tampilData();

            resetForm();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            DefaultTableModel model
                    = new DefaultTableModel();
            model.setRowCount(0);

            Connection conn = Koneksi.getKoneksi();

            String sql
                    = "SELECT krs.id, mahasiswa.nama_mahasiswa, "
                    + "matkul.nama_matkul, "
                    + "krs.semester, krs.tahun_ajaran "
                    + "FROM krs "
                    + "JOIN mahasiswa "
                    + "ON krs.nim = mahasiswa.nim "
                    + "JOIN matkul "
                    + "ON krs.kode_matkul = matkul.kode_matkul";

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nama"),
                    rs.getString("nama_matkul"),
                    rs.getString("semester"),
                    rs.getString("tahun_ajaran")
                });
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        MenuUtama menu = new MenuUtama();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {

        int row = tblKrs.getSelectedRow();
 DefaultTableModel model =
    new DefaultTableModel();
        String id =
        model.getValueAt(row,0).toString();

        Connection conn = Koneksi.getKoneksi();

        String sql =
        "DELETE FROM krs WHERE id=?";

        PreparedStatement ps =
        conn.prepareStatement(sql);

        ps.setString(1, id);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,
        "Data berhasil dihapus");

        tampilData();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(this,
        e.getMessage());
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cbMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKrs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbMahasiswa;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JComboBox<String> cbSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKrs;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
