/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Aplikasi.Koneksi;
import aplikasiakademik.MenuUtama;

/**
 *
 * @author FLEX-5
 */
public class FormJadwal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormJadwal.class.getName());

    /**
     * Creates new form FormJadwal
     */
    public FormJadwal() {
        initComponents();
        tampilMatkul();
        tampilDosen();
        tampilHari();
        tampilData();
        resetForm();
    }

    private void tampilMatkul() {

        try {
            cbMatkul.removeAllItems();

            cbMatkul.addItem("-- Pilih Mata Kuliah --");

            Connection conn = Koneksi.getKoneksi();

            Statement st = conn.createStatement();

            ResultSet rs
                    = st.executeQuery("SELECT * FROM matkul");

            while (rs.next()) {

                cbMatkul.addItem(
                        rs.getString("kode_matkul")
                        + " - "
                        + rs.getString("nama_matkul")
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void tampilDosen() {

        try {
            cbDosen.removeAllItems();

            cbDosen.addItem("-- Pilih Dosen --");

            Connection conn = Koneksi.getKoneksi();

            Statement st = conn.createStatement();

            ResultSet rs
                    = st.executeQuery("SELECT * FROM dosen");

            while (rs.next()) {

                cbDosen.addItem(
                        rs.getString("nidn")
                        + " - "
                        + rs.getString("nama_dosen")
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void tampilHari() {

        cbHari.addItem("Senin");
        cbHari.addItem("Selasa");
        cbHari.addItem("Rabu");
        cbHari.addItem("Kamis");
        cbHari.addItem("Jumat");
        cbHari.addItem("Sabtu");
    }

    private void tampilData() {

        try {
            DefaultTableModel model
                    = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Kode Mata Kuliah");
            model.addColumn("NIDN");
            model.addColumn("Hari");
            model.addColumn("Jam");
            model.addColumn("Ruang");
            model.setRowCount(0);

            Connection conn = Koneksi.getKoneksi();

            String sql
                    = "SELECT jadwal.id, "
                    + "matkul.nama_matkul, "
                    + "dosen.nama_dosen, "
                    + "jadwal.hari, jadwal.jam, jadwal.ruang "
                    + "FROM jadwal "
                    + "JOIN matkul "
                    + "ON jadwal.kode_matkul = matkul.kode_matkul "
                    + "JOIN dosen "
                    + "ON jadwal.nidn = dosen.nidn";

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nama_matkul"),
                    rs.getString("nama_dosen"),
                    rs.getString("hari"),
                    rs.getString("jam"),
                    rs.getString("ruang")
                });
            }
            tblJadwal.setModel(model);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void resetForm() {
        cbMatkul.setSelectedIndex(0);
        cbDosen.setSelectedIndex(0);
        cbHari.setSelectedIndex(0);
        txtJam.setText("");
        txtRuang.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMatkul = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbHari = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRuang = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        txtJam = new javax.swing.JTextField();
        cbDosen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("INPUT JADWAL KULIAH");

        jLabel2.setText("Kode Matkul");

        cbMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("NIDN");

        jLabel4.setText("Hari");

        jLabel5.setText("Jam");

        jLabel6.setText("Ruang");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblJadwal);

        txtJam.addActionListener(this::txtJamActionPerformed);

        cbDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMatkul, 0, 140, Short.MAX_VALUE)
                                    .addComponent(cbHari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRuang)
                                    .addComponent(txtJam)
                                    .addComponent(cbDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit)
                                .addGap(45, 45, 45)
                                .addComponent(btnHapus))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            if (cbMatkul.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Pilih Mata Kuliah terlebih dahulu!");
                return;
            }
            if (cbDosen.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Pilih Dosen terlebih dahulu!");
                return;
            }

            Connection conn = Koneksi.getKoneksi();
            String matkul
                    = cbMatkul.getSelectedItem().toString();

            String kodeMatkul
                    = matkul.split(" - ")[0];

            String dosen
                    = cbDosen.getSelectedItem().toString();

            String nidn
                    = dosen.split(" - ")[0];

            String sql
                    = "INSERT INTO jadwal "
                    + "(kode_matkul,nidn,hari,jam,ruang) "
                    + "VALUES(?,?,?,?,?)";

            PreparedStatement pst
                    = conn.prepareStatement(sql);

            pst.setString(1, kodeMatkul);
            pst.setString(2, nidn);
            pst.setString(3,
                    cbHari.getSelectedItem().toString());
            pst.setString(4,
                    txtJam.getText());
            pst.setString(5,
                    txtRuang.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Jadwal berhasil disimpan");

            tampilData();

            resetForm();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {

            int row = tblJadwal.getSelectedRow();
            DefaultTableModel model
                    = new DefaultTableModel();
            String id
                    = model.getValueAt(row, 0).toString();

            Connection conn = Koneksi.getKoneksi();

            String sql
                    = "DELETE FROM jadwal WHERE id=?";

            PreparedStatement ps
                    = conn.prepareStatement(sql);

            ps.setString(1, id);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Data berhasil dihapus");

            tampilData();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormJadwal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJadwal;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtRuang;
    // End of variables declaration//GEN-END:variables
}
