/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Aplikasi.Koneksi;

/**
 *
 * @author FLEX-5
 */
public class FormNilai extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNilai.class.getName());

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
        tampilMahasiswa();
        tampilMatkul();
    }

    private void tampilMahasiswa() {
        try {
            cbMahasiswa.removeAllItems();
            cbMahasiswa.addItem("-- Pilih Mahasiswa --");
            Connection conn = Koneksi.getKoneksi();
            Statement st = conn.createStatement();

            ResultSet rs
                    = st.executeQuery("SELECT * FROM mahasiswa");

            while (rs.next()) {

                cbMahasiswa.addItem(
                        rs.getString("nim")
                        + " - "
                        + rs.getString("nama_mahasiswa")
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void tampilMatkul() {

        try {
            cbMatkul.removeAllItems();

            cbMatkul.addItem("-- Pilih Mata Kuliah --");

            Connection conn = Koneksi.getKoneksi();

            Statement st = conn.createStatement();

            ResultSet rs
                    = st.executeQuery("SELECT * FROM matkul");

            while (rs.next()) {

                cbMatkul.addItem(
                        rs.getString("kode_matkul")
                        + " - "
                        + rs.getString("nama_matkul")
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    private void tampilData() {

        DefaultTableModel model
                = new DefaultTableModel();

        model.addColumn("ID");
        model.addColumn("NIM");
        model.addColumn("Mata Kuliah");
        model.addColumn("Nilai");

        try {

            Connection conn
                    = Koneksi.getKoneksi();

            Statement st
                    = conn.createStatement();

            String sql
                    = "SELECT nilai.id, mahasiswa.nim, "
                    + "matkul.nama_matkul, nilai.nilai "
                    + "FROM nilai "
                    + "JOIN mahasiswa "
                    + "ON nilai.nim = mahasiswa.nim "
                    + "JOIN matkul "
                    + "ON nilai.kode_matkul = matkul.kode_matkul";

            ResultSet rs
                    = st.executeQuery(sql);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nim"),
                    rs.getString("nama_matkul"),
                    rs.getString("nilai"),});

            }

            tblNilai.setModel(model);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    e);

        }
    }

    private void resetForm() {

        cbMahasiswa.setSelectedIndex(0);;
        cbMatkul.setSelectedIndex(0);;
        txtNilai.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMahasiswa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbMatkul = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Input Nilai");

        jLabel2.setText("NIM");

        cbMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMahasiswa.addActionListener(this::cbMahasiswaActionPerformed);

        jLabel3.setText("Matkul");

        cbMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Nilai");

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMahasiswa, 0, 203, Short.MAX_VALUE)
                                    .addComponent(cbMatkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNilai)))
                            .addComponent(btnSimpan)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMahasiswaActionPerformed
  
    }//GEN-LAST:event_cbMahasiswaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {

        Connection conn = Koneksi.getKoneksi();

        // AMBIL NIM
        String mahasiswa =
        cbMahasiswa.getSelectedItem().toString();

        String nim =
        mahasiswa.split(" - ")[0];

        // AMBIL KODE MATKUL
        String matkul =
        cbMatkul.getSelectedItem().toString();

        String kodeMatkul =
        matkul.split(" - ")[0];

        // QUERY
        String sql =
        "INSERT INTO nilai(nim,kode_matkul,nilai) VALUES(?,?,?)";

        PreparedStatement ps =
        conn.prepareStatement(sql);

        ps.setString(1, nim);

        ps.setString(2, kodeMatkul);

        ps.setDouble(3,
        Double.parseDouble(txtNilai.getText()));

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,
        "Data berhasil disimpan");

        tampilData();

        txtNilai.setText("");

    } catch(Exception e) {

        JOptionPane.showMessageDialog(this,
        e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbMahasiswa;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txtNilai;
    // End of variables declaration//GEN-END:variables
}
